name: layrz_logging
description: "Logging handler for Layrz apps"
version: "1.0.7"
homepage: https://github.com/goldenm-software/layrz_logging

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.4
  layrz_theme: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

platforms:
  android:
  ios:
  web:
  windows:
  linux:
  macos: